modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/gitsh01/libertyvillagers/issues"
license = "CC0-1.0"

[[mods]]
modId = "libertyvillagers"
version = "${version}"
displayName = "Liberty's Villagers"
authors = "gitsh01"
description = '''
Quality of Life improvements for villagers.
'''
logoFile = "icon.png"

[[dependencies.libertyvillagers]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libertyvillagers]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.libertyvillagers]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"